/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spfi;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roshana Pitigala
 */
public class test extends javax.swing.JFrame {

    DefaultTableModel tbl1M, tbl2M;

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        tbl1M = (DefaultTableModel) tbl1.getModel();
        tbl2M = (DefaultTableModel) tbl2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JCheckBox();
        right = new javax.swing.JCheckBox();
        marks = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        add1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setText("L");
        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        right.setText("R");
        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        getContentPane().add(marks, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 30));

        add.setText("SUM");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, 30));

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T2 C1", "T2 C2"
            }
        ));
        jScrollPane1.setViewportView(tbl2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, 160));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T1 C1", "T1 C2"
            }
        ));
        jScrollPane2.setViewportView(tbl1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 160));

        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 23, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        Vector v;
        if (left.isSelected() && right.isSelected()) {
            v = new Vector();
            v.add(name.getText());
            v.add(marks.getText());
            tbl1M.addRow(v);

            v = new Vector();
            v.add(marks.getText());
            v.add(name.getText());
            tbl2M.addRow(v);
        } else if (left.isSelected()) {
            v = new Vector();
            v.add(name.getText());
            v.add(marks.getText());
            tbl1M.addRow(v);
        } else if (right.isSelected()) {
            v = new Vector();
            v.add(name.getText());
            v.add(marks.getText());
            tbl2M.addRow(v);
        }
    }//GEN-LAST:event_add1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int marks1 = 0, marks2 = 0;
        String temp;

        marks1 = Integer.parseInt(tbl1.getValueAt(tbl1.getSelectedRow(), 1).toString());

        try {
            marks2 = Integer.parseInt(tbl2.getValueAt(tbl2.getSelectedRow(), 0).toString());
        } catch (Exception e) {
            marks2 = Integer.parseInt(tbl2.getValueAt(tbl2.getSelectedRow(), 1).toString());
        }

        JOptionPane.showMessageDialog(null, "Total : " + (marks1 + marks2));
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox left;
    private javax.swing.JTextField marks;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox right;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
}
